/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CheckingAccountRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CheckingAccountOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CheckingAccountWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author poojahiremath
 */
public class CheckingAccountWorkAreaJPanel extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount account;
    private Organization accountOrganization;
    private Enterprise enterprise;
    
   
  //  private CheckingAccountOrganization accountOrganization;


    /**
     * Creates new form CheckingAccountWorkAreaJPanel
     */
    public CheckingAccountWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem ecosystem,Enterprise enterprise) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecosystem = ecosystem;
        this.accountOrganization=organization;
        this.enterprise=enterprise;
         populateTable();

    }
    public void populateTable(){
    DefaultTableModel model = (DefaultTableModel) tblCheckingAccountRequest.getModel();
        
  
        Organization found = null;
        for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof CheckingAccountOrganization) {
                found = o;
                break;
            }
        }
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        model.setRowCount(0);
        for (WorkRequest wr : found.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof CheckingAccountWorkRequest && (wr.getReceiver() == null || wr.getReceiver() == account)) {
                CheckingAccountWorkRequest awr = (CheckingAccountWorkRequest) wr;
                Object[] row = new Object[8];
                row[0] = awr;
                row[1]=sdf.format(awr.getRequestDate());
                row[2]=awr.getsNetwork();
                row[3]=awr.getsEnterprise();
                row[4] = awr.getsMessage();
                UserAccount r = awr.getReceiver();
                row[5] = r != null ? r : "";
                row[6]=awr.getStatus();
                row[7] = awr.getSender().getUsername();
                
          
                
                //row[5]=awr.getResolveDate() != null ?  sdf.format(awr.getResolveDate()): "";
                
                model.addRow(row);
            }
        }
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProcess = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCheckingAccountRequest = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 153, 153));

        btnProcess.setBackground(new java.awt.Color(255, 255, 255));
        btnProcess.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnProcess.setForeground(new java.awt.Color(0, 153, 153));
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(0, 153, 153));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tblCheckingAccountRequest.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        tblCheckingAccountRequest.setForeground(new java.awt.Color(0, 153, 153));
        tblCheckingAccountRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Id", "Request Date", "Network", "Enterprise", "Message", "Receiver", "Status", "CustomerName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCheckingAccountRequest);

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAssign.setBackground(new java.awt.Color(255, 255, 255));
        btnAssign.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnAssign.setForeground(new java.awt.Color(0, 153, 153));
        btnAssign.setText("AssignToMe");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(44, 44, 44)
                        .addComponent(btnRefresh)
                        .addGap(27, 27, 27)
                        .addComponent(btnProcess)
                        .addGap(39, 39, 39)
                        .addComponent(btnAssign)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRefresh)
                    .addComponent(btnAssign)
                    .addComponent(btnProcess))
                .addContainerGap(235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCheckingAccountRequest.getSelectedRow();
        if (tblCheckingAccountRequest.getValueAt(selectedRow, 5).toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please assign the selected request.");
            return;

        }
        

        else if ((selectedRow >= 0) && !(tblCheckingAccountRequest.getValueAt(selectedRow, 5)).toString().isEmpty()) {
            CheckingAccountWorkRequest request = (CheckingAccountWorkRequest) tblCheckingAccountRequest.getValueAt(selectedRow, 0);

            request.setStatus("Processing");

            ProcessCheckingAccountRequestJPanel panel = new ProcessCheckingAccountRequestJPanel(userProcessContainer, request,ecosystem);
            userProcessContainer.add("ProcessAdviceJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            System.out.println("Request selected for processing of checking account ");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a request message to process.");
            return;
        }
        
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCheckingAccountRequest.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a request first");
        } else {
            CheckingAccountWorkRequest awr = (CheckingAccountWorkRequest) tblCheckingAccountRequest.getValueAt(selectedRow, 0);
            awr.setReceiver(account);
            JOptionPane.showMessageDialog(null, "Request assigned successfully");
            populateTable();
        }
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCheckingAccountRequest;
    // End of variables declaration//GEN-END:variables
}
