/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CheckingAccountRole;

import Business.Account.Account;
import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.Bank;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SavingsAccountOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ToCheckingTransferRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author poojahiremath
 */
public class RequestToSavingsJPanel extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private Organization organization;
    private Enterprise enterprise;

    /**
     * Creates new form RequestToSavingsJPanel
     */
    public RequestToSavingsJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business,Organization organization,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.account = account;
        this.organization=organization;
        this.enterprise=enterprise;
        populateBank();
    }
public void populateBank(){
    Customer cus = (Customer)business.getCustomerDirectory().searchCustomer(account.getUsername());
        for(Account acc: cus.getAccountList()){
        if (acc.getType().equalsIgnoreCase("Savings")){
        cmbBank.addItem(acc.getBankName());
        }
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestDealJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        balTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbBank = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 153, 153));

        requestDealJButton.setBackground(new java.awt.Color(255, 255, 255));
        requestDealJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        requestDealJButton.setForeground(new java.awt.Color(0, 153, 153));
        requestDealJButton.setText("Request Deal");
        requestDealJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestDealJButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(255, 255, 255));
        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(0, 153, 153));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Message");

        balTF.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        balTF.setForeground(new java.awt.Color(0, 153, 153));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Enter the balance to be requested");

        cmbBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBankActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Bank");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbBank, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(balTF, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(backJButton)
                        .addGap(50, 50, 50)
                        .addComponent(requestDealJButton)))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(balTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestDealJButton)
                    .addComponent(backJButton))
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestDealJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestDealJButtonActionPerformed

       // String message = messageTF.getText();
        double balance= Double.parseDouble(balTF.getText());
        String name=cmbBank.getSelectedItem().toString();
        System.out.println("printing balance"+balance);

        if((balTF.getText()).equals("")||(balTF.getText()).isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter something to send.");
            return;
        }
        ToCheckingTransferRequest request = new  ToCheckingTransferRequest();
       // request.setMessage(message);
        request.setBalance(balance);
        request.setSender(account);
        request.setStatus("Sent");
        System.out.println("request is ready");
        String bankName = cmbBank.getSelectedItem().toString();
        
        for(Network n: business.getNetworkList()){
        for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
            if(e.getName().equalsIgnoreCase(bankName)){
                for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                if (o instanceof SavingsAccountOrganization){
                        o.getWorkQueue().addWorkRequest(request);
                }
                }
            }
        }
        
        } 
account.getWorkQueue().addWorkRequest(request);
        JOptionPane.showMessageDialog(null, "Message sent");

       // JOptionPane.showMessageDialog(null, "org is savings ac org."+this.organization);

        
       
       /* ((SavingsAccountOrganization)this.organization).getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "the resquest has been sent by."+request.getSender().toString());*/

        
      // Organization org = null;
     /*  System.out.println(business.getUserDirectory().getUserAccountList());
       //for(UserAccount  :business.getUserDirectory().getUserAccountList()){
           for (WorkRequest list :account.getWorkQueue().getWorkRequestList()){
               System.out.println(list.getSender());
               org=list.getOrganization();
               System.out.println("org ??????"+org);
               if(org instanceof SavingsAccountOrganization ){
                   break;     
               } 
           }     
      //  }
       if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Request message sent");
        }
        //System.out.println("ecosystem list---"+business.getOrganizationDirectory().getOrganizationList());
        //System.out.println("enterprise list-----"+enterprise.getOrganizationDirectory().getOrganizationList());
        
        /*for (Organization organiz :business.getOrganizationDirectory().getOrganizationList()){
            System.out.println("what is organiz"+organiz);
            if (organiz instanceof SavingsAccountOrganization){
                org = organiz;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }*/

        JOptionPane.showMessageDialog(null, "Message not sent");
    }//GEN-LAST:event_requestDealJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RequestTransferJPanel dwjp = (RequestTransferJPanel) component;
        dwjp.populateRequestTable1();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void cmbBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBankActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField balTF;
    private javax.swing.JComboBox cmbBank;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton requestDealJButton;
    // End of variables declaration//GEN-END:variables
}
