/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Coins.Coins;
import Business.Customer.iText;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Mail;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import com.itextpdf.text.DocumentException;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.util.Timer;
import java.util.TimerTask;
import javax.mail.MessagingException;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import javax.swing.JOptionPane;


/**
 *
 * @author mansigandhi
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem ecosystem;
    private Enterprise enterprise;
    private Organization organization;

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem, Enterprise enterprise,Organization organizatio) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecosystem = ecosystem;
        this.enterprise = enterprise;
        this.organization = organizatio;
        populateTable();
    }

      public void populateTable() {
//          System.out.println("Here1");
        Timer timer = new Timer();
        TimerTask tsk = new TimerTask() {
            
            @Override
            public void run() {
//                System.out.println("Here");
                DefaultTableModel model = (DefaultTableModel) liveContentsTable.getModel();
                model.setRowCount(0);
                for (Coins c : ecosystem.getCoinsCatalog().getCoinsList()) {
//                    System.out.println("A---->"+c.getSymbol());
                    Object[] row = new Object[2];
                    row[0] = c.getdPrice();
                    row[1] = c.getSymbol();
                    model.addRow(row);
                }
            }
        };
        timer.schedule(tsk, 0, 50000);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        liveContentsTable = new javax.swing.JTable();
        btnPriceAlert = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCoinSymbol = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAdvice = new javax.swing.JButton();
        btnTradeRequest = new javax.swing.JButton();
        btnViewRequest = new javax.swing.JButton();
        btnAccount1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSell = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        liveContentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RATE", "QUOTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(liveContentsTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 504, 210));

        btnPriceAlert.setBackground(new java.awt.Color(255, 255, 255));
        btnPriceAlert.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnPriceAlert.setForeground(new java.awt.Color(0, 153, 153));
        btnPriceAlert.setText("Submit");
        btnPriceAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceAlertActionPerformed(evt);
            }
        });
        add(btnPriceAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Symbol");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, -1, -1));
        add(txtCoinSymbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 154, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Price Alert");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 411, 188, -1));
        add(txtRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 154, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Rate");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        btnAdvice.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnAdvice.setForeground(new java.awt.Color(0, 153, 153));
        btnAdvice.setText("Advice");
        btnAdvice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdviceActionPerformed(evt);
            }
        });
        add(btnAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, -1));

        btnTradeRequest.setBackground(new java.awt.Color(255, 255, 255));
        btnTradeRequest.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnTradeRequest.setForeground(new java.awt.Color(0, 153, 153));
        btnTradeRequest.setText("Future Investments");
        btnTradeRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTradeRequestActionPerformed(evt);
            }
        });
        add(btnTradeRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, -1));

        btnViewRequest.setBackground(new java.awt.Color(255, 255, 255));
        btnViewRequest.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnViewRequest.setForeground(new java.awt.Color(0, 153, 153));
        btnViewRequest.setText("View Request");
        btnViewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestActionPerformed(evt);
            }
        });
        add(btnViewRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 210, -1));

        btnAccount1.setBackground(new java.awt.Color(255, 255, 255));
        btnAccount1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnAccount1.setForeground(new java.awt.Color(0, 153, 153));
        btnAccount1.setText("Account");
        btnAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccount1ActionPerformed(evt);
            }
        });
        add(btnAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 170, -1));

        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Analysis Report Generation");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, -1));

        btnSell.setForeground(new java.awt.Color(0, 153, 153));
        btnSell.setText("Sell Coins");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });
        add(btnSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPriceAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceAlertActionPerformed
        // TODO add your handling code here:
        String coinSymbol = "\""+txtCoinSymbol.getText()+"\"";
        double Rate = Double.parseDouble(txtRate.getText());

        // Recipient's email ID needs to be mentioned.
        String username = account.getUsername();
        String emailID = ecosystem.getCustomerDirectory().searchCustomer(username).getsEmailId();
        System.out.println(emailID);
        String to = emailID;
        DecimalFormat df = new DecimalFormat("##.##");
        for (Coins c : ecosystem.getCoinsCatalog().getCoinsList()) {
//            System.out.println("Email");
            if ((c.getSymbol().equalsIgnoreCase(coinSymbol)) && ((Double.parseDouble(df.format(c.getdPrice()))) == Rate)) {
                try {
//                    System.out.println("Email 2");
                    if (Mail.sendMail("juhitwilight@gmail.com", "edwardbella", "Price Alert For The Coin", to)) {
                        System.out.println("Email Sent");
                        break;
                    } else {
                        System.out.println("error");
                    }
                } catch (MessagingException ex) {
                    Logger.getLogger(CustomerWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_btnPriceAlertActionPerformed

    private void btnAdviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdviceActionPerformed
        // TODO add your handling code here:
        AdviceJPanel panel = new AdviceJPanel(userProcessContainer, ecosystem, account);
        userProcessContainer.add("AdviceJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnAdviceActionPerformed

    private void btnViewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestActionPerformed
        // TODO add your handling code here:
        ViewRequestJPanel panel = new ViewRequestJPanel(userProcessContainer, account, ecosystem);
        userProcessContainer.add("ViewRequestJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewRequestActionPerformed

    private void btnAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccount1ActionPerformed
        // TODO add your handling code here:
        CreateAccountJPanel panel = new CreateAccountJPanel(userProcessContainer,account ,ecosystem,enterprise,organization);
        userProcessContainer.add("CreateAccountJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnAccount1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            iText.generatePDF(account,ecosystem);
        } catch (DocumentException ex) {
            Logger.getLogger(CustomerWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTradeRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTradeRequestActionPerformed
        // TODO add your handling code here:
        FutureInvestmentJPanel panel = new FutureInvestmentJPanel(userProcessContainer,ecosystem,account);
        userProcessContainer.add("FutureInvestmentJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnTradeRequestActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        // TODO add your handling code here:
        SellCoinsJPanel panel = new SellCoinsJPanel(userProcessContainer,account ,ecosystem);
        userProcessContainer.add("SellCoinsJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnSellActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount1;
    private javax.swing.JButton btnAdvice;
    private javax.swing.JButton btnPriceAlert;
    private javax.swing.JButton btnSell;
    private javax.swing.JButton btnTradeRequest;
    private javax.swing.JButton btnViewRequest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable liveContentsTable;
    private javax.swing.JTextField txtCoinSymbol;
    private javax.swing.JTextField txtRate;
    // End of variables declaration//GEN-END:variables
}
