/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Coins.Coins;
import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Investment.Investment;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juhi Navalekar
 */
public class FutureInvestmentJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
private EcoSystem ecosystem;
private UserAccount account;
private Customer c;
    /**
     * Creates new form FutureInvestmentJPanel
     */
    public FutureInvestmentJPanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount account) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.ecosystem = ecosystem;
        this.account = account;
        this.c = (Customer) ecosystem.getCustomerDirectory().searchCustomer(account.getUsername());
        populateFutureTable();
    }
    public void populateFutureTable(){
     DefaultTableModel model = (DefaultTableModel) tblFutureInvestments.getModel();

        model.setRowCount(0);
        //Customer c = (Customer) ecosystem.getCustomerDirectory().searchCustomer(account.getUsername());

        for (Investment item : c.getFutureInvestment()) {
            Object[] row = new Object[4];
            Coins coin = item.getCoin();
            row[0] = item;
            row[1] = coin.getdPrice();
            row[2] = item.getQuantity();
            row[3] = item.investmentAmount();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFutureInvestments = new javax.swing.JTable();
        btnRequestInvest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Future Investments");

        tblFutureInvestments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coin Type", "Price", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tblFutureInvestments);

        btnRequestInvest.setBackground(new java.awt.Color(255, 255, 255));
        btnRequestInvest.setForeground(new java.awt.Color(0, 153, 153));
        btnRequestInvest.setText("Request Investment");
        btnRequestInvest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestInvestActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(281, 281, 281))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRequestInvest)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnRequestInvest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestInvestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestInvestActionPerformed
        // TODO add your handling code here:
        int selectRow = tblFutureInvestments.getSelectedRow();
        if (selectRow<0){
        JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
        else{
            Investment i = (Investment)tblFutureInvestments.getValueAt(selectRow, 0);
            BuyCoinsJPanel panel = new BuyCoinsJPanel(userProcessContainer,ecosystem,account,i,c);
            userProcessContainer.add("BuyCoinsJPanel", panel);
            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnRequestInvestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestInvest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFutureInvestments;
    // End of variables declaration//GEN-END:variables
}
