/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Account.Account;
import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Bank;
import Business.Enterprise.PrivateBroker;
import Business.Network.Network;
import Business.Organization.AdvisoryOrganization;
import Business.Organization.Organization;
import Business.Organization.SavingsAccountOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SavingAccountWorkRequest;
import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mansigandhi
 */
public class SavingsAccountJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
private UserAccount account;
private EcoSystem ecosystem;
    /**
     * Creates new form SavingsAccountJPanel
     */
    public SavingsAccountJPanel(JPanel userProcessContainer,UserAccount account ,EcoSystem ecosystem) {
        initComponents();
        this.account=account;
        this.ecosystem=ecosystem;
        this.userProcessContainer=userProcessContainer;
         populateNetworks();
         networkJComboBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                populateEnterprise((Network) networkJComboBox.getSelectedItem());

            }
        });
         
    }
    private void populateNetworks() {
        //get a list of networks from network directory
        for (Network n : ecosystem.getNetworkList()) {
            networkJComboBox.addItem(n);
        }

    }

    private void populateEnterprise(Network n) {
        //get list of enterprise under the network who can advice which is investment bank or private broker
        enterpriseNameJComboBox.removeAllItems();
        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
            if ((e instanceof Bank)) {
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                    if (o instanceof SavingsAccountOrganization) {
                        enterpriseNameJComboBox.addItem(e);
                    }
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewAccount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enterpriseNameJComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        messageTF = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        RequestAdvice = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 153, 153));

        btnViewAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnViewAccount.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnViewAccount.setForeground(new java.awt.Color(0, 153, 153));
        btnViewAccount.setText("View Saving Accounts");
        btnViewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAccountActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Add Savings Account");

        networkJComboBox.setBackground(new java.awt.Color(255, 255, 255));
        networkJComboBox.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        networkJComboBox.setForeground(new java.awt.Color(0, 153, 153));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Network");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Enterprise");

        enterpriseNameJComboBox.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Message");

        messageTF.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        messageTF.setForeground(new java.awt.Color(0, 153, 153));
        messageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTFActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        RequestAdvice.setBackground(new java.awt.Color(255, 255, 255));
        RequestAdvice.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        RequestAdvice.setForeground(new java.awt.Color(0, 153, 153));
        RequestAdvice.setText("Create Account(Req)");
        RequestAdvice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestAdviceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(544, 544, 544))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterpriseNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewAccount)
                            .addComponent(RequestAdvice))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(enterpriseNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(messageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(RequestAdvice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void messageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTFActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void RequestAdviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestAdviceActionPerformed
        // TODO add your handling code here:
        String cusname=account.getUsername();
        Enterprise e1 = (Enterprise) enterpriseNameJComboBox.getSelectedItem();
        System.out.println(e1);
        
        
       List<Customer> c=ecosystem.getCustomerDirectory().getCustomerList();
       for(Customer cus:c)
       {
           if(cus.getUseraccount().getUsername().equalsIgnoreCase(cusname)){
//            for(Account a:cus.getAccountList())
//           {
//               System.out.println(a.getBankName());
//               
//               if(a.getBankName().equalsIgnoreCase(e1.toString())){
//                   System.out.println("They are equal");
//                   
//                   JOptionPane.showMessageDialog(null, "Savings account already present");
//                   break;
//                   
//               }
//               else{
                       SavingAccountWorkRequest awr = new SavingAccountWorkRequest();
        awr.setsMessage(messageTF.getText());
        awr.setsNetwork(networkJComboBox.getSelectedItem().toString());
        awr.setsEnterprise(enterpriseNameJComboBox.getSelectedItem().toString());
        awr.setSender(account);
        awr.setRequestDate(new Date());
        awr.setStatus("Requested");
        awr.setType("Savings");
        Network n = (Network) networkJComboBox.getSelectedItem();
        Enterprise e = (Enterprise) enterpriseNameJComboBox.getSelectedItem();
        for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof SavingsAccountOrganization) {
                o.getWorkQueue().getWorkRequestList().add(awr);
            }
        }
        account.getWorkQueue().getWorkRequestList().add(awr);

        JOptionPane.showMessageDialog(null, "Request message sent");
                   
              // }
                   
               //}
           }
               
           }
           
          
       

    
    }//GEN-LAST:event_RequestAdviceActionPerformed

    private void btnViewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAccountActionPerformed
        // TODO add your handling code here:
        ViewSavingsAccountJPanel panel = new ViewSavingsAccountJPanel(userProcessContainer,account ,ecosystem);
        userProcessContainer.add("ViewSavingsAccountJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequestAdvice;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewAccount;
    private javax.swing.JComboBox enterpriseNameJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField messageTF;
    private javax.swing.JComboBox networkJComboBox;
    // End of variables declaration//GEN-END:variables
}
