/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FinancialServiceRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FinancialServiceOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author poojahiremath
 */
public class FinancialServiceWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount account;
    private FinancialServiceOrganization financialServiceOrganization;
    private Enterprise enterprise;

    /**
     * Creates new form FinancialServiceWorkAreaJPanel
     */
    public FinancialServiceWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.enterprise = enterprise;
        this.financialServiceOrganization = (FinancialServiceOrganization)organization;
        lblUsername.setText(account.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnBuyRequest = new javax.swing.JButton();
        txtSellCoins = new javax.swing.JButton();
        btnBorrow = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Financial Service Work Area");

        btnBuyRequest.setBackground(new java.awt.Color(255, 255, 255));
        btnBuyRequest.setForeground(new java.awt.Color(0, 153, 153));
        btnBuyRequest.setText("Buy Coins Request");
        btnBuyRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyRequestActionPerformed(evt);
            }
        });

        txtSellCoins.setBackground(new java.awt.Color(255, 255, 255));
        txtSellCoins.setForeground(new java.awt.Color(0, 153, 153));
        txtSellCoins.setText("Sell Coins Request");
        txtSellCoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSellCoinsActionPerformed(evt);
            }
        });

        btnBorrow.setForeground(new java.awt.Color(0, 153, 153));
        btnBorrow.setText("Borrow Coins");
        btnBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome,");

        lblUsername.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuyRequest)
                        .addGap(49, 49, 49)
                        .addComponent(txtSellCoins)
                        .addGap(66, 66, 66)
                        .addComponent(btnBorrow)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUsername))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuyRequest)
                    .addComponent(txtSellCoins)
                    .addComponent(btnBorrow))
                .addContainerGap(350, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyRequestActionPerformed
        // TODO add your handling code here:
        BuyCoinsWorkJPanel panel = new BuyCoinsWorkJPanel(userProcessContainer, account,financialServiceOrganization,enterprise,business);
        userProcessContainer.add("BuyCoinsWorkJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnBuyRequestActionPerformed

    private void txtSellCoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSellCoinsActionPerformed
        // TODO add your handling code here:
        SellCoinsWorkJPanel panel = new SellCoinsWorkJPanel(userProcessContainer, account,financialServiceOrganization,enterprise,business);
        userProcessContainer.add("SellCoinsWorkJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_txtSellCoinsActionPerformed

    private void btnBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowActionPerformed
        // TODO add your handling code here:
        BorrowCoinsJPanel panel = new BorrowCoinsJPanel(userProcessContainer, account,financialServiceOrganization,enterprise,business);
        userProcessContainer.add("BorrowCoinsJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnBorrowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrow;
    private javax.swing.JButton btnBuyRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JButton txtSellCoins;
    // End of variables declaration//GEN-END:variables
}
