/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FinancialServiceRole;

import Business.Account.Account;
import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Investment.Investment;
import Business.Investment.InvestmentDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SellCoinsWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pramathesh Navalekar
 */
public class ProcessSellRequestJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
private SellCoinsWorkRequest cwr;
private EcoSystem business;
private Enterprise enterprise;
private UserAccount account;
    /**
     * Creates new form ProcessSellRequestJPanel
     */
    public ProcessSellRequestJPanel(JPanel userProcessContainer, SellCoinsWorkRequest cwr,EcoSystem business,Enterprise enterprise,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.cwr = cwr;
        this.business = business;
        this.enterprise= enterprise;
        this.account = account;
        txtCrypto.setText(cwr.getSellCoins().getCoin().getSymbol());
        txtPrice.setText(String.valueOf(cwr.getSellCoins().getCoin().getdPrice()));
        txtQuantity.setText(String.valueOf(cwr.getSellCoins().getQuantity()));
        txtAmount.setText(String.valueOf(cwr.getSellCoins().investmentAmount()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCrypto = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        btnProcess = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Process Sell Request");

        jLabel2.setText("Cryto Coin:");

        jLabel3.setText("Quantity:");

        jLabel4.setText("Amount:");

        txtCrypto.setEditable(false);
        txtCrypto.setBackground(new java.awt.Color(255, 255, 255));
        txtCrypto.setEnabled(false);

        txtQuantity.setEditable(false);
        txtQuantity.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantity.setEnabled(false);

        txtAmount.setEditable(false);
        txtAmount.setBackground(new java.awt.Color(255, 255, 255));
        txtAmount.setEnabled(false);

        btnProcess.setBackground(new java.awt.Color(255, 255, 255));
        btnProcess.setForeground(new java.awt.Color(0, 153, 153));
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        jLabel5.setText("Price:");

        txtPrice.setEditable(false);
        txtPrice.setBackground(new java.awt.Color(255, 255, 255));
        txtPrice.setEnabled(false);

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnReject.setBackground(new java.awt.Color(255, 255, 255));
        btnReject.setForeground(new java.awt.Color(0, 153, 153));
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addGap(43, 43, 43)
                            .addComponent(btnReject)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                            .addComponent(btnProcess))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCrypto, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                .addComponent(txtPrice)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtAmount, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCrypto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcess)
                    .addComponent(btnBack)
                    .addComponent(btnReject))
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
       userProcessContainer.remove(this);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.previous(userProcessContainer);
       Component[] components = userProcessContainer.getComponents();
       for (Component c : components) {
           if (c instanceof SellCoinsWorkJPanel) {
               SellCoinsWorkJPanel sellcoinsWorkJPanel = (SellCoinsWorkJPanel) c;
               sellcoinsWorkJPanel.populateTable();
           }
       }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
       cwr.setStatus("Rejected");
       cwr.setResolveDate(new Date());
       cwr.setMessage("Rejected");
       btnProcess.setEnabled(false);
       JOptionPane.showMessageDialog(null, "Request is rejected");
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:

        cwr.setStatus("Completed");
        cwr.setResolveDate(new Date());
        btnReject.setEnabled(false);
        for (Investment i : enterprise.getEnterpriseInvestment()) {
            if (i.getCoin().getSymbol().matches(cwr.getSellCoins().getCoin().getSymbol())) {
                int iAvailableQnty = i.getQuantity() + (cwr.getSellCoins().getQuantity());
                i.setQuantity(iAvailableQnty);
            }
        }
        double bal = (enterprise.getEnterpriseAcnt().getBal())-(cwr.getdAmount());
        enterprise.getEnterpriseAcnt().setBal(bal);
        Customer c = (Customer) business.getCustomerDirectory().searchCustomer(cwr.getSender().getUsername());
        for(Investment custInst : c.getCoinDetails()){
            if(custInst.getCoin().getSymbol().matches(cwr.getSellCoins().getCoin().getSymbol())){
            int sellQnty = custInst.getQuantity()-(cwr.getSellCoins().getQuantity());           
            custInst.setQuantity(sellQnty);
            }
            //add new in list
            else{
            c.getCoinDetails().add(cwr.getSellCoins());
            }
        }
        //update balance
        for (Account a:c.getAccountList()){
            if(a.getBankName().matches(cwr.getCustomerAccount())&& a.getType().matches("Checking")){
                double balance = a.getBal() + (cwr.getdAmount());
                a.setBal(balance);
            }
        }
        InvestmentDirectory id = new InvestmentDirectory();
            id.setInvestmentList(cwr.getSellCoins());
            id.setType("Sell");
            c.getCurrentInvestment().add(id);
        JOptionPane.showMessageDialog(null, "Request processed successfully");
        System.out.println("Financial Organization employee sells the coins of customer");
    }//GEN-LAST:event_btnProcessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCrypto;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
