/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Components;
import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.Role.CustomerRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Juhi Navalekar
 */
public class AddCustomerJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
CustomerDirectory customerDirectory;
ImageIcon img;
    /**
     * Creates new form AddCustomerJPanel
     */
    public AddCustomerJPanel(JPanel userProcessContainer,CustomerDirectory customerDirectory) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.customerDirectory=customerDirectory;
        populatecmbSex();
        cmbSex.setSelectedIndex(0);
    }
    //populate the items in combo box of Sex(Male/Female)
    private void populatecmbSex() {
        cmbSex.addItem("Male");
        cmbSex.addItem("Female");
    }
    
    private void resetFields() {

        txtFirstName.setText("");
        txtLastName.setText("");
        txtEmailId.setText("");
        txtMobileNumber.setText("");
        txtAge.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        cmbSex.setSelectedIndex(0);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCustId = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbSex = new javax.swing.JComboBox();
        txtMobileNumber = new javax.swing.JTextField();
        txtEmailId = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("New Customer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 49, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Customer Id:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 147, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("First Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 193, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Last Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 239, 82, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Age:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 279, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Mobile Number:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 167, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Email Id:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 217, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Username:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 263, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("Password:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 309, -1, -1));

        txtCustId.setEditable(false);
        add(txtCustId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 142, 142, -1));

        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyPressed(evt);
            }
        });
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 188, 142, -1));

        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLastNameKeyPressed(evt);
            }
        });
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 234, 142, -1));

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeKeyTyped(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 274, 142, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Sex:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 324, -1, -1));

        cmbSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSexActionPerformed(evt);
            }
        });
        add(cmbSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 314, 142, -1));

        txtMobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileNumberKeyTyped(evt);
            }
        });
        add(txtMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 162, 143, -1));
        add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 212, 143, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 258, 143, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 556, -1, -1));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 153, 153));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 392, -1, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 304, 143, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexActionPerformed

    private void txtMobileNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileNumberKeyTyped
        // TODO add your handling code here:
        char t = evt.getKeyChar();
        if (!(Character.isDigit(t) || t == KeyEvent.VK_BACK_SPACE || t == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMobileNumberKeyTyped

    private void txtAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyTyped
        // TODO add your handling code here:
        char t = evt.getKeyChar();
        if (!(Character.isDigit(t) || t == KeyEvent.VK_BACK_SPACE || t == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAgeKeyTyped

    private void txtFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)) {
            txtFirstName.setEditable(false);
            txtFirstName.setBackground(Color.red);
        } else {
            txtFirstName.setEditable(true);
            txtFirstName.setBackground(Color.WHITE);

        }
    }//GEN-LAST:event_txtFirstNameKeyPressed

    private void txtLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)) {
            txtLastName.setEditable(false);
            txtLastName.setBackground(Color.red);
        } else {
            txtLastName.setEditable(true);
            txtLastName.setBackground(Color.WHITE);

        }
    }//GEN-LAST:event_txtLastNameKeyPressed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String password = String.valueOf(txtPassword.getPassword());
        //store password as character
        char[] spwd = password.toCharArray();
        if (Components.isTextEmpty(txtFirstName.getText()) || Components.isTextEmpty(txtLastName.getText())||Components.isTextEmpty(txtAge.getText())
                || Components.isTextEmpty(txtMobileNumber.getText()) || Components.isTextEmpty(txtEmailId.getText())
                || Components.isTextEmpty(txtUsername.getText()) || Components.isTextEmpty(txtPassword.getPassword().toString())) {

            JOptionPane.showMessageDialog(null, "All the text fields are mandatory");

        } else if (username.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Username");
        } else if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Password");
        } else if (spwd.equals(" ")) {
            JOptionPane.showMessageDialog(null, "Space is not allowed");
        } else if (spwd.length < 8) {
            JOptionPane.showMessageDialog(null, "Select password atleast 8 charcter");
        } else if (txtMobileNumber.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "Mobile number must be 10 digits");
        } else if (Integer.parseInt(txtAge.getText()) > 100 || Integer.parseInt(txtAge.getText()) < 18) {
            JOptionPane.showMessageDialog(null, "Please enter Age (between 18 to 100)");
        } else if (String.valueOf(cmbSex.getSelectedItem()).equalsIgnoreCase("Select")) {
            JOptionPane.showMessageDialog(null, "Please select the Gender");
        } else if (!Components.validateEmail(txtEmailId.getText())) {
            JOptionPane.showMessageDialog(null, "Please enter valid Email address");
        }  else {
            Customer cSearch = customerDirectory.searchCustomer(username);
            if (cSearch != null) {
                JOptionPane.showMessageDialog(null, "Someone has already used this username");
            } else {
                Customer c = new Customer();
                /*UserAccount ua = new UserAccount();
                ua.setIsActive(true);
                ua.setUsername(username);
                ua.setPassword(password);
                ua.setRole(new CustomerRole());
                ua.setPerson(c);*/
                c.getUseraccount().setIsActive(true);
                c.getUseraccount().setUsername(username);
                c.getUseraccount().setPassword(password);
                c.getUseraccount().setRole(new CustomerRole());

                c.setsFirstName(txtFirstName.getText());
                c.setsLastName(txtLastName.getText());
                c.setiAge(Integer.parseInt(txtAge.getText()));
                c.setsSex(String.valueOf(cmbSex.getSelectedItem()));
                c.setlMobileNumber(Long.parseLong(txtMobileNumber.getText()));
                c.setsEmailId(txtEmailId.getText().trim());
                c.setRoletype(Role.RoleType.Customer);
                //c.setUseraccount(ua);

                //set person profile image
                //c.setiProfilePicture((ImageIcon) lblProfilePic.getIcon());
                c.setiProfilePicture(img);
                customerDirectory.addCustomer(c);
                JOptionPane.showMessageDialog(null, "Customer added successfully");
                resetFields();
                System.out.println("Customer is created");
            }
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:      
       userProcessContainer.remove(this);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.previous(userProcessContainer);
       Component[] components = userProcessContainer.getComponents();
       for (Component c : components) {
           if (c instanceof ManageCustomerJPanel) {
               ManageCustomerJPanel manageCustomerPanel = (ManageCustomerJPanel) c;
               manageCustomerPanel.populateTable();
           }
       }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCustId;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
