/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Investment.Investment;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateComboBox();
       // populateEnterpriseName();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = network.getName();
                row[2] = enterprise.getEnterpriseType().getValue();

                model.addRow(row);
            }
        }
    }

    private void populateComboBox() {
        networkJComboBox.removeAllItems();
        enterpriseTypeJComboBox.removeAllItems();

        for (Network network : system.getNetworkList()) {
            networkJComboBox.addItem(network);
        }
        
        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            enterpriseTypeJComboBox.addItem(type);
        }
        
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enterpriseTypeJComboBox = new javax.swing.JComboBox();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        btnEnterpriseManageAdmin = new javax.swing.JButton();
        nameTF = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseJTable.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        enterpriseJTable.setForeground(new java.awt.Color(0, 153, 153));
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 35, 640, 180));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Network");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        networkJComboBox.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        networkJComboBox.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 136, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Enterprise Type");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        enterpriseTypeJComboBox.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        enterpriseTypeJComboBox.setForeground(new java.awt.Color(0, 153, 153));
        enterpriseTypeJComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                enterpriseTypeJComboBoxItemStateChanged(evt);
            }
        });
        enterpriseTypeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseTypeJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(enterpriseTypeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 136, -1));

        submitJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(0, 153, 153));
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(0, 153, 153));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, -1));

        btnEnterpriseManageAdmin.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnEnterpriseManageAdmin.setForeground(new java.awt.Color(0, 153, 153));
        btnEnterpriseManageAdmin.setText("Manage Enterprise Admin");
        btnEnterpriseManageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterpriseManageAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnterpriseManageAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        nameTF.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        nameTF.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 136, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
private boolean containsSpecialCharacter(String s) {
        boolean status = false;
        Pattern pattern = Pattern.compile("[a-zA-Z0-9]*");

        //String str = "abc@";
        Matcher matcher = pattern.matcher(s);

        if (!matcher.matches()) {
            status = true;
        }
        return status;
    }

    private boolean containsDigit(String s) {
        boolean containsDigit = false;

        if (s != null && !s.isEmpty()) {
            for (char c : s.toCharArray()) {
                if (containsDigit = Character.isDigit(c)) {
                    break;
                }
            }
        }

        return containsDigit;
    }
    private void enterpriseTypeJComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_enterpriseTypeJComboBoxItemStateChanged
        // TODO add your handling code here:
        //populateEnterpriseName();
    }//GEN-LAST:event_enterpriseTypeJComboBoxItemStateChanged

    private void enterpriseTypeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseTypeJComboBoxActionPerformed
        // TODO add your handling code here:
        //populateEnterpriseName();
    }//GEN-LAST:event_enterpriseTypeJComboBoxActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnEnterpriseManageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterpriseManageAdminActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(userProcessContainer, system);
        userProcessContainer.add("manageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEnterpriseManageAdminActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        Network network = (Network) networkJComboBox.getSelectedItem();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) enterpriseTypeJComboBox.getSelectedItem();

        if (network == null || type == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }

        String name = nameTF.getText();
        boolean isInteger = containsDigit(name);
        boolean isSpecial = containsSpecialCharacter(name);
        if (network.getEnterpriseDirectory().SearchEnterprise(name, type)) {

            JOptionPane.showMessageDialog(null, "Enterprise name of this type already present", "Warning", JOptionPane.INFORMATION_MESSAGE);
            nameTF.setText(" ");

        } else if (nameTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enterprise name  can not be blank", "Warning", JOptionPane.INFORMATION_MESSAGE);
            nameTF.setText(" ");
        } else if (isInteger == true) {
            JOptionPane.showMessageDialog(null, "Enterprise name cannot be Numbers", "Warning", JOptionPane.INFORMATION_MESSAGE);
            nameTF.setText(" ");
        } else if (isSpecial == true) {
            JOptionPane.showMessageDialog(null, "Enterprise name cannot have special characters", "Warning", JOptionPane.INFORMATION_MESSAGE);
            nameTF.setText(" ");
        } else {
            Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type);
        enterprise.getEnterpriseAcnt().setBankName("bofa");
         enterprise.getEnterpriseAcnt().setBal(1000000);
            Investment i = new Investment();
         i.getCoin().setSymbol("EUR");
         //i.getCoin().setCryptoCoinName("EUR");
         i.getCoin().setdPrice(0.8810);
         i.setdPrice(0.8810);
         i.setQuantity(20);
         enterprise.getEnterpriseInvestment().add(i);
         Investment i1 = new Investment();
         i1.getCoin().setSymbol("ZAR");
         //i1.getCoin().setCryptoCoinName("ZAR");
         i1.getCoin().setdPrice(14.13);
         i1.setdPrice(14.13);
         i1.setQuantity(10);
         enterprise.getEnterpriseInvestment().add(i1);
         Investment i2 = new Investment();
         i2.getCoin().setSymbol("TRY");
        // i2.getCoin().setCryptoCoinName("TRY");
         i2.getCoin().setdPrice(5.33);
         i2.setdPrice(5.33);
         i2.setQuantity(10);
         enterprise.getEnterpriseInvestment().add(i2);
         Investment i3 = new Investment();
         i3.getCoin().setSymbol("THB");
        // i3.getCoin().setCryptoCoinName("THB");
         i3.getCoin().setdPrice(32.85);
         i3.setdPrice(32.85);
         i3.setQuantity(25);
         enterprise.getEnterpriseInvestment().add(i3);
            populateTable();
            JOptionPane.showMessageDialog(null, "Enterprise name added successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);

        }
        System.out.println("Activity : Enterprise created successfully");
    }//GEN-LAST:event_submitJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnEnterpriseManageAdmin;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JComboBox enterpriseTypeJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
