/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;


import Business.EcoSystem;
import Business.Network.Network;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author poojahiremath
 */



    /**
     * Creates new form AddNetworkJPanel
     */
  
public class ViewNetworkJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Network network;
    private EcoSystem ecosystem;

    /**
     * Creates new form ViewNetworkJPanel
     */
    public ViewNetworkJPanel(JPanel userProcessContainer, Network n,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network=n;
        this.ecosystem=ecosystem;
        networkName1.setText(network.getName());
        
        //populateNetworkTable();
    }
private boolean containsSpecialCharacter(String s)
{
    boolean status =false ;
    Pattern pattern = Pattern.compile("[a-zA-Z0-9]*");
 
      //String str = "abc@";
      Matcher matcher = pattern.matcher(s);
 
      if (!matcher.matches()) {
          status=true;
      } 
      return status;
}
private boolean containsDigit(String s) {
    boolean containsDigit = false;

    if (s != null && !s.isEmpty()) {
        for (char c : s.toCharArray()) {
            if (containsDigit = Character.isDigit(c)) {
                break;
            }
        }
    }

    return containsDigit;
}
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        networkName1 = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 153, 153));
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 175, -1, -1));

        networkName1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        networkName1.setForeground(new java.awt.Color(0, 153, 153));
        networkName1.setEnabled(false);
        add(networkName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 200, 40));

        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 153, 153));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 175, -1, -1));

        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 500, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Country Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 114, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        boolean status=ecosystem.searchNetwork(networkName1.getText());
        String name=networkName1.getText();
        boolean isInteger=containsDigit(name);
        boolean isSpecial=containsSpecialCharacter(name);

        if(status == true)
        {
            JOptionPane.showMessageDialog(null, "Network already present", "Warning", JOptionPane.INFORMATION_MESSAGE);
            networkName1.setText(" ");
        }
        else if(networkName1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "The Network field can not be blank", "Warning", JOptionPane.INFORMATION_MESSAGE);
            networkName1.setText(" ");
        }
        else if(isInteger==true){
            JOptionPane.showMessageDialog(null, "The Network field cannot be Numbers", "Warning", JOptionPane.INFORMATION_MESSAGE);
            networkName1.setText(" ");
        }
        else if(isSpecial==true){
            JOptionPane.showMessageDialog(null, "The Network field cannot have special characters", "Warning", JOptionPane.INFORMATION_MESSAGE);
            networkName1.setText(" ");
        }
        else
        {
            try{

                networkName1.setEditable(false);
                btnSave.setEnabled(false);
                btnUpdate.setEnabled(true);
                network.setName(networkName1.getText());

                JOptionPane.showMessageDialog(null, "Network updated successfully");
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "Exception Occured");

            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        networkName1.setEditable(true);
        networkName1.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
 /*void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) networkJTable.getModel();

        model.setRowCount(0);
        for (Network network : ecosystem.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getName();
            model.addRow(row);
        }
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField networkName1;
    // End of variables declaration//GEN-END:variables
}
