/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Components;
import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pramathesh Navalekar
 */
public class ViewCustomerJPanel extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    private Customer customer;
    private CustomerDirectory customerDirectory;
    private UserAccount account;
    /**
     * Creates new form ViewCustomerJPanel
     */
    public ViewCustomerJPanel(JPanel userProcessContainer, Customer customer, CustomerDirectory customerDirectory, UserAccount account) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.customerDirectory = customerDirectory;
        this.customer=customer;
        this.account= account;
        populatecmbSex();
        populateData();
    }

    public void populateData() {
        txtCustId.setEnabled(false);
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtUsername.setEnabled(false);
        txtPassword.setEnabled(false);
        txtMobileNumber.setEnabled(false);
        txtEmailId.setEnabled(false);
        txtAge.setEnabled(false);
        cmbSex.setEnabled(false);

        txtCustId.setText(String.valueOf(customer.getId()));
        txtFirstName.setText(customer.getsFirstName());
        txtLastName.setText(customer.getsLastName());
        txtUsername.setText(customer.getUseraccount().getUsername());
        txtPassword.setText("");
        txtMobileNumber.setText(String.valueOf(customer.getlMobileNumber()));
        txtEmailId.setText(customer.getsEmailId());
        cmbSex.setSelectedItem(customer.getsSex());
        txtAge.setText(String.valueOf(customer.getiAge()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCustId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        cmbSex = new javax.swing.JComboBox();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("View Customer");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 59, 119, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Customer Id:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 146, -1, -1));

        txtCustId.setEditable(false);
        txtCustId.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtCustId.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(txtCustId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 142, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Mobile Number:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 154, -1, -1));

        txtMobileNumber.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtMobileNumber.setForeground(new java.awt.Color(0, 153, 153));
        txtMobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileNumberKeyTyped(evt);
            }
        });
        jPanel1.add(txtMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 148, 150, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("First Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 193, -1, -1));

        txtFirstName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(0, 153, 153));
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 187, 142, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Last Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 82, -1));

        txtLastName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(0, 153, 153));
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLastNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 234, 142, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Age:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 281, -1, -1));

        txtAge.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtAge.setForeground(new java.awt.Color(0, 153, 153));
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeKeyTyped(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 275, 142, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Email Id:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 205, -1, -1));

        txtEmailId.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtEmailId.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 199, 150, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Username:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 252, -1, -1));

        txtUsername.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 153, 153));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 246, 150, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("Password:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 299, -1, -1));

        txtPassword.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 293, 150, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Sex:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 320, -1, -1));

        cmbSex.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cmbSex.setForeground(new java.awt.Color(0, 153, 153));
        cmbSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSexActionPerformed(evt);
            }
        });
        jPanel1.add(cmbSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 316, 142, -1));

        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 153, 153));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 414, -1, -1));

        btnSave.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 153, 153));
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 414, -1, -1));

        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 628, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMobileNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileNumberKeyTyped
        // TODO add your handling code here:
        char t = evt.getKeyChar();
        if (!(Character.isDigit(t) || t == KeyEvent.VK_BACK_SPACE || t == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMobileNumberKeyTyped

    private void txtFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)) {
            txtFirstName.setEditable(false);
            txtFirstName.setBackground(Color.red);
        } else {
            txtFirstName.setEditable(true);
            txtFirstName.setBackground(Color.WHITE);

        }
    }//GEN-LAST:event_txtFirstNameKeyPressed

    private void txtLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)) {
            txtLastName.setEditable(false);
            txtLastName.setBackground(Color.red);
        } else {
            txtLastName.setEditable(true);
            txtLastName.setBackground(Color.WHITE);

        }
    }//GEN-LAST:event_txtLastNameKeyPressed

    private void txtAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyTyped
        // TODO add your handling code here:
        char t = evt.getKeyChar();
        if (!(Character.isDigit(t) || t == KeyEvent.VK_BACK_SPACE || t == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAgeKeyTyped

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void cmbSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        //txtCustId.setEnabled(false);
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtUsername.setEnabled(true);
        txtPassword.setEnabled(true);
        txtMobileNumber.setEnabled(true);
        txtEmailId.setEnabled(true);
        txtAge.setEnabled(true);
        cmbSex.setEnabled(true);
        //lblProfilePic.setIcon(customer.getiProfilePicture());
        populatecmbSex();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        System.out.println("Activity :view and update customer details");
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String password = String.valueOf(txtPassword.getPassword());
        //store password as character
        char[] spwd = password.toCharArray();
        if (Components.isTextEmpty(txtFirstName.getText()) || Components.isTextEmpty(txtLastName.getText())||Components.isTextEmpty(txtAge.getText())
            || Components.isTextEmpty(txtMobileNumber.getText()) || Components.isTextEmpty(txtEmailId.getText())
            || Components.isTextEmpty(txtUsername.getText()) || Components.isTextEmpty(txtPassword.getPassword().toString())) {

            JOptionPane.showMessageDialog(null, "All the text fields are mandatory");

        } else if (username.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Username");
        } else if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Password");
        } else if (spwd.equals(" ")) {
            JOptionPane.showMessageDialog(null, "Space is not allowed");
        } else if (spwd.length < 8) {
            JOptionPane.showMessageDialog(null, "Select password atleast 8 charcter");
        } else if (txtMobileNumber.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "Mobile number must be 10 digits");
        } else if (Integer.parseInt(txtAge.getText()) > 100 || Integer.parseInt(txtAge.getText()) < 18) {
            JOptionPane.showMessageDialog(null, "Please enter Age (between 18 to 100)");
        } else if (String.valueOf(cmbSex.getSelectedItem()).equalsIgnoreCase("Select")) {
            JOptionPane.showMessageDialog(null, "Please select the Gender");
        } else if (!Components.validateEmail(txtEmailId.getText())) {
            JOptionPane.showMessageDialog(null, "Please enter valid Email address");
        }  else {
            Customer cSearch = customerDirectory.searchCustomer(username);
            /*if (cSearch != null) {
                JOptionPane.showMessageDialog(null, "Someone has already used this username");
            } else {*/

                customer.setsFirstName(txtFirstName.getText());
                customer.setsLastName(txtLastName.getText());
                customer.setiAge(Integer.parseInt(txtAge.getText()));
                customer.setsSex(String.valueOf(cmbSex.getSelectedItem()));
                customer.setlMobileNumber(Long.parseLong(txtMobileNumber.getText()));
                customer.setsEmailId(txtEmailId.getText().trim());
                customer.getUseraccount().setUsername(username);
                if(String.valueOf(txtPassword.getPassword()).length()>0)
                customer.getUseraccount().setPassword(String.valueOf(txtPassword.getPassword()));
                //set person profile image
               

                JOptionPane.showMessageDialog(null, "Customer updated successfully");
                //resetFields();
                btnSave.setEnabled(false);
                btnUpdate.setEnabled(true);

            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component[] components = userProcessContainer.getComponents();
        for (Component c : components) {
            if (c instanceof ManageCustomerJPanel) {
                ManageCustomerJPanel manageCustomerPanel = (ManageCustomerJPanel) c;
                manageCustomerPanel.populateTable();
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void populatecmbSex() {
        cmbSex.addItem("Male");
        cmbSex.addItem("Female");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbSex;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCustId;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
